version: "3"
services:
  ocserv:
    container_name: ocserv
    image: farshadnikfetrat/ocserv:latest
    privileged: true
    ports:
    - 1080:443/tcp
    - 1080:443/udp
    volumes:
    - ${PWD}/conf/:/etc/ocserv/

